exclude: [.git, documentation, makefile, static/package-lock.json, static/package.json, static/node_modules, README.md, scripts]
permalink: pretty
future: false
sass:
  style: compressed
  sass_dir: static/src/sass