#!/usr/bin/env bash
set -e # halt script on error

npm install
./node_modules/.bin/modernizr --config=modernizr-config.json --dest=static/js/modernizr.js

bundle exec jekyll build
if [[ "$TRAVIS_BRANCH" != "www" ]]; then
  echo "On beta branch, doing beta things..."
  cp ./_site/robots.txt.template ./_site/robots.txt
fi

# Test the site
bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --disable-external

# Deploy to Firebase
FB=./node_modules/.bin/firebase
if [[ "$TRAVIS_BRANCH" == "www" ]]; then
  $FB deploy --non-interactive --token=$RBH_FIREBASE_TOKEN --project=rutherford-nj
else
  $FB deploy --non-interactive --token=$RBH_FIREBASE_TOKEN --project=rutherford-nj-beta-site
fi
