#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
if [[ "$TRAVIS_BRANCH" == "beta" ]]; then
  echo "On beta branch, doing beta things..."
  cp ./_site/robots.txt.template ./_site/robots.txt
fi

# Run URL change script so static.rutherford-nj.com domain is used consistently.
cd _site
./scripts/url-switch.sh
cd ..

# Test the site
bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --disable-external
