#!/usr/bin/env bash
set -e # halt script on error

env

bundle exec jekyll build
if [[ "$TRAVIS_BRANCH" == "beta" ]]; then
  cp ./_site/robots.txt.template ./_site/robots.txt
fi
bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html --disable-external
