name: Deploy Site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout site
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build the site and deploy
      env:
        SITE_WORKSPACE: ${{ github.workspace }}
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
        echo '${{ secrets.BETA_SA_CREDENTIALS }}' > $HOME/gcloud.json
        export FIREBASE_PROJECT="rutherford-nj-beta-site"
        [[ "$GITHUB_REF" == refs/heads/www ]] && \
          echo '${{ secrets.PROD_SA_CREDENTIALS }}' > $HOME/gcloud.json && \
          export FIREBASE_PROJECT="rutherford-nj" && \
          rm $SITE_WORKSPACE/robots.txt
        make deploy
