name: Links

on:
  schedule:
    - cron: 42 3 * * 0
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.9
        with:
          args: >
            "./**/*.md" "./**/*.html" "./**/*.yml"
            --verbose --no-progress --exclude-mail
            --timeout 60
            --exclude https://apis.google.com/
            --exclude https://sheets.googleapis.com/
            --exclude https://clients6.google.com/
            --exclude https://fonts.gstatic.com/
            --exclude https://www.njmcdirect.com/
            --exclude https://twitter.com/%7B%7B%20include.username%20%7D%7D
            --exclude "https://player.vimeo.com/video/*"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          assignees: bogosj
          labels: report, automated issue
