name: Links

on:
  schedule:
    - cron: 42 3 * * 0
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build site
        run: make prod
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.1
        with:
          args: >
            _site/**/*.html
            --verbose --no-progress --exclude-mail
            --insecure
            --max-retries 10
            --exclude https://apis.google.com/
            --exclude https://sheets.googleapis.com/
            --exclude https://clients6.google.com/
            --exclude https://fonts.gstatic.com/
            --exclude https://www.njmcdirect.com/
            --exclude "https://twitter.com/*"
            --exclude "https://player.vimeo.com/video/*"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          assignees: bogosj
          labels: report, automated issue
